### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by cbluth** [hvxahv/hvx#160]
Hello, interesting project. I was looking for an architectural document, or some document explaining how it works, but information is scarce.

How does it work, and what are the features and benefits?

**Comment by disism** [comment]
@cbluth Thank you for your interest.
I'm very sorry to say that the project is still in development and not yet operational, but I am working on the architecture documentation and I will provide an architecture document describing how it works as soon as possible.
For now you can follow this link [APIs_METHODS](https://github.com/hvxahv/hvx/blob/main/docs/APIs_METHODS.md) to see the API you want to build. 
And also see the gRPC design at [APIs_PROTOBUF](https://github.com/hvxahv/hvx/tree/main/APIs/proto/v1alpha1) to see the designed microservices protopub API.

The current goal is to build a zone-centric social system, build an account system based on the Activitypub protocol, and integrate IPFS as a storage system for some of the services, I will also integrate matrix.io protocol in the client as an instant messaging system, and design the project so that everything is zone-centric and for personal privacy.

If you need to follow up, you can continue to reply or use the contact form at the bottom of this page to contact me at https://disism.com/about
